### PR TITLE
feat: adding possibility to have dev or prod ignore files configuration

### PR DESCRIPTION
**Pull request by bsvobodny**
Adding the possibility to have 2 ignore files configuration depending on NODE_ENV value
- NODE_ENV === "development" => 'dev'
- NODE_ENV === "production" = 'prod'

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
Hi @bsvobodny! Great idea - thanks for this!
To further expand on it - what do you think about making it modular (i.e. any `NODE_ENV`)?
In the case config is an object, `getPatterns` would get patterns that our under object key NODE_ENV.

This would allow more flexibility in cases where NODE_ENV is custom. (for any reason, i.e. "test")

**Comment by bsvobodny** [comment]
> Hi @bsvobodny! Great idea - thanks for this! To further expand on it - what do you think about making it modular (i.e. any `NODE_ENV`)? In the case config is an object, `getPatterns` would get patterns that our under object key NODE_ENV.
> 
> This would allow more flexibility in cases where NODE_ENV is custom. (for any reason, i.e. "test")

Let me see if I understood well.
What you suggest is that the config could look something like that : 
``` 
  "parcelIgnore": {
    "development":[
        "env.js",
        "some.lib.js",
        "jquery.js"
      ],
    "production":[
        "env.js",
        "some.lib.js",
        "jquery.js"
      ],
    "test":[
        "env.js",
        "some.lib.js",
        "jquery.js"
      ],
	"someRandomValue":[
        "env.js",
        "some.lib.js",
        "jquery.js"
      ]
  }
``` 
And in the code => 

``` 
const getPatterns = function (config = []) {

  if (Array.isArray(config)) {
    return config;
  } else {
    return config[process.env.NODE_ENV] || []    
  }
};
``` 
In this case it will get
1. The config if it's an array (retro-compatible)
2.  the `process.env.NODE_ENV` config
3.  an empty array

**Comment by VladimirMikulic** [comment]
@bsvobodny correct!

**Comment by bsvobodny** [comment]
@VladimirMikulic modification done 😉

**Comment by VladimirMikulic** [comment]
Thank you @bsvobodny! I just noticed you're submitting a PR from your master branch.
Could you create a separate branch so I can merge this?

**Comment by bsvobodny** [comment]
> Thank you @bsvobodny! I just noticed you're submitting a PR from your master branch. Could you create a separate branch so I can merge this?

I created a new PR #6 , is it OK ?

**Pull request closed without merging**
