### PR TITLE
Fix Regex patterns in examples in README.md

### PR DESCRIPTION
**Pull request by simonpai**
Tested with `2.1.1`

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
Hi @simonpai! I appreciate you making the PR. Sorry for a late response here.
Current README examples work for me so could you please describe the intention behind this change?

Thanks!

**Comment by VladimirMikulic** [comment]
Thanks for fast reply @simonpai. I guess you're referring to images regex?
That was just simple example of ignoring everything with `images` path.
Of course, everyone is free to customize what they would like to ignore.

**Comment by simonpai** [comment]
I will explain with some counter examples:

```
new RegExp("images\/*.*").test('imagesxyz/') // true
new RegExp("{{*.*}}").test('{}}') // true
```

The original examples are absolutely correct. The only issue is just that the first `*` make them less accurate.

**Comment by VladimirMikulic** [comment]
Updates published in v2.1.3.
Thanks again @simonpai!

**Pull request merged**
