### PR TITLE
feat: adding possilibity to use NODE_ENV value as map keys for ignore files configuration

### PR DESCRIPTION
**Pull request by bsvobodny**
New PR that doesn't come fromt master, same as #5

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
🎉🎉🎉

**Comment by bsvobodny** [comment]
It was a pleasure !
Thanks a lot to you 😉

**Comment by bsvobodny** [comment]
@VladimirMikulic you changed my PR and make a mistake. 
When the parcelIgnore is an array but there is no entry for the current NODE_ENV value
```
const { parcelIgnore = [] } = pkgJSON;
const regexpPatterns = Array.isArray(parcelIgnore)
  ? parcelIgnore
  : parcelIgnore[process.env.NODE_ENV];
```
`regexpPatterns` will be undefined, it should be an empty array instead.

The code below should do the trick 😉 

```
const { parcelIgnore = [] } = pkgJSON;
const regexpPatterns = Array.isArray(parcelIgnore)
  ? parcelIgnore
  : parcelIgnore[process.env.NODE_ENV] || []; 
```

**Comment by VladimirMikulic** [comment]
Hi @bsvobodny. If there is no `parcelIgnore`, we default to an empty array.
`const { parcelIgnore = [] } = pkgJSON;`

**Comment by bsvobodny** [comment]
@VladimirMikulic the issue is not when the `parcelIgnore` is undefined but when you have 
```
parcelIgnore: {
	'production' : [
		'somescript.js'
	]
}
```

But `NODE_ENV` is 'development'

**Comment by VladimirMikulic** [comment]
@bsvobodny that makes sense - good catch! Fix published in v2.1.1.
I added you as the author: https://github.com/VladimirMikulic/parcel-resolver-ignore/commit/dd38a19b8898fc3a43748524884dd8de76130d81

**Pull request merged**
