### PR TITLE
Declare parcel/plugin dependency

### PR DESCRIPTION
**Pull request by mischnic**
See https://github.com/VladimirMikulic/parcel-resolver-ignore/issues/12

### CODE REVIEW

**Comment by VladimirMikulic** [comment]
Thanks @mischnic for taking the time to submit the PR.
I guess I still don't fully understand the issue here -  why is it required to specify `@parcel/plugin` in dependencies?
I just tried my plugin with latest Parcel v2.10.3 and it works without any issues.
Perhaps the user in #12 uses "non-standard/hackish" custom build of some sort?

**Comment by mischnic** [comment]
Yes this might work fine, but it would definitely break once you have pnpm/Yarn modern-style strict dependency enforcement.

A Parcel plugin is just a regular npm package that is `require`-d by Parcel. So you should declare all dependencies you use in your code (`@parcel/plugin`).

And you don't need/shouldn't have `@parcel/core` as a devdepdency for the same reason: you don't import it in the plugin.

> Perhaps the user in https://github.com/VladimirMikulic/parcel-resolver-ignore/issues/12 uses "non-standard/hackish" custom build of some sort?

Yes, they must have, probably a globally `parcel` install.

**Comment by VladimirMikulic** [comment]
That makes sense @mischnic.
Could you please add this information to Parcel official documentation? (perhaps [Authoring Plugins page](https://parceljs.org/plugin-system/authoring-plugins/#loading-configuration))
It would also be helpful if you could make official Parcel plugin template repository so the community is aware of this (and other practices).

**Comment by VladimirMikulic** [comment]
Added in https://github.com/VladimirMikulic/parcel-resolver-ignore/commit/ed337adb2af76b8e874b433bfdc9fde946bbbc1c.

**Pull request closed without merging**
